import { Inter } from 'next/font/google'
import './globals.css'
import { MovieProvider } from '@/context/movieContext'
import Navbar from '@/components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Movies OMDb API',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <MovieProvider>
        <body className={`${inter.className} p-4 bg-gray-800 text-white max-w-[1500px] m-auto`}>
          <header className='bg-gray-700 py-4 md:py-0 px-20 mb-5 '>
            <Navbar />
          </header>
          <main className='flex justify-center h-[calc(screen-5rem)] w-full bg-gray-700 px-4 md:px-10 pb-4 md:py-4'>
            {children}
          </main>
        </body>
      </MovieProvider>
    </html>
  )
}
